# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hydroponics.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'hydroponics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import nanopb_pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hydroponics.proto\x1a\x0cnanopb.proto\"\x7f\n\nSensorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x13\n\x0blight_level\x18\x03 \x01(\x02\x12\x18\n\tph_levels\x18\x04 \x03(\x02\x42\x05\x92?\x02\x10\x05\x12\x1b\n\x0crelay_states\x18\x05 \x03(\x08\x42\x05\x92?\x02\x10\x05\"\xac\x01\n\x07\x43ommand\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.Command.CommandType\x12\x13\n\x0brelay_index\x18\x02 \x01(\r\x12\x17\n\x0fph_sensor_index\x18\x03 \x01(\r\x12\x1c\n\x14ph_calibration_value\x18\x04 \x01(\x02\"1\n\x0b\x43ommandType\x12\x10\n\x0cTOGGLE_RELAY\x10\x00\x12\x10\n\x0c\x43\x41LIBRATE_PH\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydroponics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['ph_levels']._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['ph_levels']._serialized_options = b'\222?\002\020\005'
  _globals['_SENSORDATA'].fields_by_name['relay_states']._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['relay_states']._serialized_options = b'\222?\002\020\005'
  _globals['_SENSORDATA']._serialized_start=35
  _globals['_SENSORDATA']._serialized_end=162
  _globals['_COMMAND']._serialized_start=165
  _globals['_COMMAND']._serialized_end=337
  _globals['_COMMAND_COMMANDTYPE']._serialized_start=288
  _globals['_COMMAND_COMMANDTYPE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
